version: 0.0
os: linux
files:
  - source: /
    destination: /myapp
permissions:
  - object: /myapp/startApp.sh
    mode: 777
hooks:
  ApplicationStop:
      echo inside application stop
    - location: stopApp.sh
      timeout: 60
      runas: root
ApplicationStart:
      echo inside application start
    - location: startApp.sh
      timeout: 60
      runas: root
