version: 0.0
os: linux
files:
  - source: /
    destination: /myapp
permissions:
  - object: /myapp
    pattern: "st*"
    mode: 777
hooks:
ApplicationStart:
    - location: stopApp.sh
      timeout: 60
      runas: root
ApplicationStart:
    - location: startApp.sh
      timeout: 60
      runas: root

